### ISSUE TITLE
Missing generated code core 3.6

### ISSUE THREAD

**Issue by LuisCRSousa** [Microchip-MPLAB-Harmony/core#10]
Updated all packages to last version: csp and core to 3.6 from 3.5.2 and mplab x gives me this error.

`../src/config/project/driver/i2c/src/drv_i2c.c: In function '_DRV_I2C_PLibCallbackHandler':
../src/config/project/driver/i2c/src/drv_i2c.c:372:20: error: 'DRV_I2C_TRANSFER_OBJ' has no member named 'errors'
         transferObj->errors = dObj->i2cPlib->errorGet();
                    ^
../src/config/project/driver/i2c/src/drv_i2c.c:374:23: error: 'DRV_I2C_TRANSFER_OBJ' has no member named 'errors'
         if(transferObj->errors == DRV_I2C_ERROR_NONE)
                       ^
../src/config/project/driver/i2c/src/drv_i2c.c: In function 'DRV_I2C_ErrorGet':
../src/config/project/driver/i2c/src/drv_i2c.c:751:58: error: 'DRV_I2C_TRANSFER_OBJ' has no member named 'errors'
             errors = dObj->transferObjPool[transferIndex].errors;
                                                          ^
../src/config/project/driver/i2c/src/drv_i2c.c:752:49: error: 'DRV_I2C_TRANSFER_OBJ' has no member named 'errors'
             dObj->transferObjPool[transferIndex].errors = DRV_I2C_ERROR_NONE;
                                                 ^
../src/config/project/driver/i2c/src/drv_i2c.c: In function '_DRV_I2C_WriteReadTransferAdd':
../src/config/project/driver/i2c/src/drv_i2c.c:838:16: error: 'DRV_I2C_TRANSFER_OBJ' has no member named 'errors'
     transferObj->errors       = DRV_I2C_ERROR_NONE;`

**Comment by vishalnxt** [comment]
@LuisCRSousa , you will have to regenerate the project with the latest packages. There is a change in the signature of the error get API for USART and I2C drivers. Please refer the release notes - https://github.com/Microchip-MPLAB-Harmony/core/blob/master/release_notes.md#new-features

**Comment by LuisCRSousa** [comment]
I always regenerate all code with the latest packages. If I downgrade core to 3.5.2 this problem does not happen.
Also deleted all packages and redownloaded again. Same problem.

**Comment by vishalnxt** [comment]
@LuisCRSousa , could you try regenerating and building one of the sample application available at https://github.com/Microchip-MPLAB-Harmony/core/tree/master/apps/driver/i2c/async

**Comment by dsettu** [comment]
@LuisCRSousa, We are not able to reproduce the issue. Please try with v3.7.0 release. thanks.
