### ISSUE TITLE
Stuck in loop unlocking flash.

### ISSUE THREAD

**Issue by stantheman103** [Microchip-MPLAB-Harmony/core#14]
I'm a bit new to Github, so please bare with me.
I am trying to get the drv_at25df working with a PIC32MZ2048EFH.
The drivers all compile fine, but the code gets stuck when unlocking the flash.

Debugging shows it stuck on this line:
while (gDrvAT25DFObj.transferStatus != DRV_AT25DF_TRANSFER_STATUS_COMPLETED);
line 662 within DRV_AT25DF_Open function.

I believe it is writing the SPI data out, but as only a single byte is written, it is written immediately rather than using the interrupt routine. Therefore the callback is not made and the flag is not set.

I'm not sure if the _DRV_AT25DF_WriteEnable should re-enable the flag following a successful write of a single byte?

Any help would be appreciated.

Best regards,
Robert

**Comment by vishalnxt** [comment]
@stantheman103 , the unlock command consist of a write enable command (1 byte) followed by the global unlock command (2 bytes) and reading the status (1 command byte transmitted out and 2 bytes status received).
How many bytes do you see on the SPI bus? You can either use an oscilloscope or increment a counter in the SPI transmit interrupt and see how many bytes are getting transmitted out? Further can you check if the WP and Hold pins are pulled high.
Also, what is the SPI clock frequency?

**Comment by stantheman103** [comment]
Thank you for the fast reply. I'll have a look with a logic analyser. The bus speed is currently 1Mhz (as I wanted to get it working below 10Mhz. We are using a 6 lead 25AA02E48 so we don't have the WP and Hold pins. I will get a logic analyser on the chip and do some further investigations and report back.

**Comment by stantheman103** [comment]
I can see the SPI transmitting the first 8 bits (0x06) via a logic analyser. The SPI IRQ is not responding. I will have to look into the SPI driver further as to why this is not happening.
Thanks for the help.
