### ISSUE TITLE
i2c_eeprom/at24 incompatible with I2C Driver

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/core#19]
The AT24 can not be used with the I2C Driver. So it is not possible to use other I2C Modules, which usese the i2c driver, because the i2c peripheral is already block by AT24 Driver.

![grafik](https://user-images.githubusercontent.com/7147324/95292885-a60b8980-0872-11eb-8fdd-29eaadf58201.png)

**Comment by vishalnxt** [comment]
@pustekuchen91 , yes currently AT24 driver works only with I2C PLIB and hence the PLIB instance cannot be used for other I2C devices on the bus. However, there is a demo example that talks to AT24 EEPROM using I2C driver available at -  <application-repo-path>/apps/driver/i2c/async/i2c_eeprom/firmware. For example [i2c_eeprom demo](https://github.com/Microchip-MPLAB-Harmony/core_apps_sam_d21_da1/tree/master/apps/driver/i2c/async/i2c_eeprom)
This demo can be taken as a starting point. Increase the number of clients in the I2C driver configuration depending on the number of devices on the bus.

**Comment by pustekuchen91** [comment]
thank you @vishalnxt that demo project is a good hint.
