### ISSUE TITLE
Driver CANFD controler on SPI bus

### ISSUE THREAD

**Issue by raf6410** [Microchip-MPLAB-Harmony/core#20]
Hi,

I would like to add some extra CANFD channel via SPI on my custom board.
The controleur CANFD is MCP2518FD.
I would like to have driver bloc in Harmony 3.
I tried to understand how it make but i'm a newbie in harmony.

Could you help me ?

**Comment by jigneshmoradiya1** [comment]
Hi,

Harmony 3 supports CAN/CAN-FD PLIB (Peripheral Library) only for on-chip CAN/CAN-FD controller for Microchip 32-bit MCU/MPU devices.
As per requirement, The following option can be considered to add external CAN-FD controller via SPI (SPI to CAN-FD) using MCP2518FD:
- Create MPLAB X Project using Harmony 3 configurations and add H3 SPI Driver in the project.
- Develop SPI to CAN-FD Application using H3 SPI driver to interface with MCP2518FD as per project requirement (Reference example code which can be helpful for developing SPI to CAN-FD application - https://ww1.microchip.com/downloads/en/DeviceDoc/mcp25xxfd_demo_h2_rel.zip)

Thank you.

**Comment by raf6410** [comment]
Thanks for your help.

In using a custom board with a DsPIC32MK.
I'm already use the 4 CAN channels inside the PIC.
I know this exemple, i have already tried to merge this exemple with my code.

Other question, How "harmony communty" choose new  driver to add ?
For exemple, if i would like to create a driver " External CANFD controller" I can push here myself or it will be "Validate" by Harmony community"?
