### ISSUE TITLE
Driver SPI, PIC32MZ (EF) TransferSetup missing options.

### ISSUE THREAD

**Issue by youpko** [Microchip-MPLAB-Harmony/core#23]
I ran into a problem with the SPI driver (Synchronous mode) for PIC32MZ1024EFK.

I want to change the SPI clock rate at runtime using the `DRV_SPI_TransferSetup()` but the option to set the SPI hardware to 32-bit mode is missing. There is no enum for `DRV_SPI_DATA_BITS_32`.

After browsing through the `DRV_SPI_WriteReadTransfer` source I found that the DMA setup also would require a change.
- `DRV_SPI_WriteReadTransfer` checks for 8bits and if it is any other it is set to 16bit and does the word-to-byte conversion, it doesn't check for for the 32bit case.
- `drvSPI*remapDataBits` in `initialization.c` doesn't contain a remap for the 32bit case.
- `_DRV_SPI_StartDMATransfer` also has no setup for 32-bit DMA.

**Comment by vishalnxt** [comment]
Thank you @youpko for reporting the issue. I will create an internal ticket to get this fixed.

**Comment by vishalnxt** [comment]
@youpko , the SPI driver is updated to support 32-bit data transfers. I am closing this ticket. Feel free to re-open it in case you find any issues.
