### ISSUE TITLE
I2C Slave Support

### ISSUE THREAD

**Issue by jorisbeurden** [Microchip-MPLAB-Harmony/core#24]
I cannot for the life of me get the I2C slave working. If I connect a slave configured interface to the driver it automatically to master mode. Is there any timeline for adding a slave mode driver? This is keeping me from porting to HarmonyV3

**Comment by vishalnxt** [comment]
@jorisbeurden , the I2C drivers currently only support master mode of operation. The I2C peripheral library (PLIB) however should have support for both master and slave modes. Can you tell us the device part number? Based on the part number I can share a link to PLIB based I2C slave application/demo example.

**Comment by jorisbeurden** [comment]
@vishalnxt Thank you for the reply, I did indeed find the possibility to work directly trough the PLIB but I hoped there would be a driver somewhere that I missed. I am using a PIC32MX250F128D and I hope the examples make it easy enough to port. Although actual drivers would be a better solution and I might wait until they are available before I port.
