### ISSUE TITLE
Static variable lastUsedIndex is used simultaneously by any spi driver

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/core#27]
Hello @[vishalnxt](https://github.com/vishalnxt) ,

with https://github.com/Microchip-MPLAB-Harmony/core/commit/ecafccc50664d1b84a6fbea8b3b9b5a8fbfb3823 you introduced a new bug to the SPI Driver.

`lastUsedIndex` (https://github.com/Microchip-MPLAB-Harmony/core/blob/master/driver/spi/src/async/drv_spi.c.ftl#L326) is a static variable and is not part of the DRV_SPI_OBJ. 
If two SPI Drivers willl be used with different sizes of DRV_SPI_QUEUE_SIZE_IDX* , the optimization will be broken. 
`lastUsedIndex` will be used simultaneously for any spi driver instance.

**Comment by vishalnxt** [comment]
@pustekuchen91 , Yes, thanks for pointing that out. I am raising a ticket to get it fixed.

**Comment by vishalnxt** [comment]
@pustekuchen91 , were you able to resolve the issue with the latest core v3.11.1 release?

**Comment by vishalnxt** [comment]
@pustekuchen91 , closing the issue as it is resolved. Please feel free to reopen if you are still running into issue.
