### ISSUE TITLE
FILE SYSTEM module doesn't load in latest release V3.13.0

### ISSUE THREAD

**Issue by TheHogfather562** [Microchip-MPLAB-Harmony/core#29]
Started a new project with a PIC32MZ1064DAR179 and was loading in the harmony modules, and the FILE SYSTEM module doesn't appear after adding it in the project graph. It doesn't appear in the Project graph.

**Comment by jigneshmoradiya1** [comment]
@TheHogfather562 , MPLAB® Harmony 3 SYS_FS File System service has dependency on FileX in the core v3.13.0 release. Hence FileX (https://github.com/azure-rtos/filex) need to be downloaded using MCC content manager (OR clone it using command - **git clone https://github.com/azure-rtos/filex.git**)

Please refer the release notes for the same https://github.com/Microchip-MPLAB-Harmony/core/blob/master/release_notes.md

**Comment by TheHogfather562** [comment]
Thanks for this!

If it's a requirement can it not be auto downloaded as a dependency in MCC?

Thank you for your help!

**Comment by jigneshmoradiya1** [comment]
Yes, All dependency repositories are automatically downloaded by the MCC content manager. Try to clone/update core repo using MCC content manager.
