### ISSUE TITLE
PIC32MZ EF Harmony3 SQICS1 used by default

### ISSUE THREAD

**Issue by lucapascarella** [Microchip-MPLAB-Harmony/core#3]
drv_sst26.c has an issue with PIC32MZ (probably others MCU). The line SQI_BDCTRL_SQICS_CS1 is used by default and it seems there are no options in Harmony 3 Configurator to use SQICS0 instead of SQICS1.
When every occurrence of SQI_BDCTRL_SQICS_CS1 is substitute with SQI_BDCTRL_SQICS_CS0 the CS0 line work properly.
 
Luca

**Comment by amitraddi** [comment]
@lucapascarella Thank you for posting the issue. This will be fixed in future releases.
