### ISSUE TITLE
mpfs.c missed cache handling

### ISSUE THREAD

**Issue by lucapascarella** [Microchip-MPLAB-Harmony/core#5]
It may be not a novelty since the problem was present in the previous Harmony version, but I think it is essential to bring attention now.

The _mpfs.c_ misses a cache guard when used together with PIC32MZ and SST26 SQI in DMA or PIO mode. In that configuration, the SQI writes in non-cacheable space and _mpfs.c_, instead, uses cacheable addresses creating unpredictable behaviors that often prevent even to mount the file system.

Below a temporary fix to that issue acting on the _mpfs.c_.
Fix enabled with _SQI_CACHE_WORKAROUND_ macro.

[mpfs.c.zip](https://github.com/Microchip-MPLAB-Harmony/core/files/3674847/mpfs.c.zip)

**Comment by dsettu** [comment]
@lucapascarella , Thank you for your feedback, it will be fixed in v3.6 release.

**Comment by dsettu** [comment]
@lucapascarella , This issue is fixed now. Please check it out and close. thanks.
