### ISSUE TITLE
Concurrency issue with drv_at25df.c

### ISSUE THREAD

**Issue by lucapascarella** [Microchip-MPLAB-Harmony/core#8]
The _drv_at25df.c_ has a concurrency issue when the SPI interrupt is generated too fast.

Since __DRV_AT25DF_Handler_ called by __SPIEventHandler_ is invoked by the SPI interrupt routine as soon as the transmission is terminated there is an unexpected possibility that the _gDrvAT25DFObj.state_ is modified after the execution of __DRV_AT25DF_Handler_.
In this scenario, __DRV_AT25DF_Handler_ handles the default state because _DRV_AT25DF_STATE_READ_CMD_ADDR_ is not implemented.

This issue happens frequently when _DRV_AT25DF_Read_ is called in an RTOS context.

A temporary workaround is to set the state to _gDrvAT25DFObj.state = DRV_AT25DF_STATE_READ_DATA;_ before call __DRV_AT25DF_WriteMemoryAddress_ in _DRV_AT25DF_Read_.

`bool DRV_AT25DF_Read(
    const DRV_HANDLE handle,
    void* rxData,
    uint32_t rxDataLength,
    uint32_t address
)
{
    bool isRequestAccepted = false;

    if((handle == DRV_HANDLE_INVALID) || (handle > 0) || (rxData == NULL) \
            || (rxDataLength == 0) || (gDrvAT25DFObj.transferStatus == DRV_AT25DF_TRANSFER_STATUS_BUSY))
    {
        return isRequestAccepted;
    }

    if ((address + rxDataLength) > gDrvAT25DFObj.flashSize)
    {
        /* Writing past the flash size results in an error */
        return isRequestAccepted;
    }

    gDrvAT25DFObj.transferStatus = DRV_AT25DF_TRANSFER_STATUS_BUSY;

    /* save the request */
    gDrvAT25DFObj.nPendingBytes = rxDataLength;
    gDrvAT25DFObj.bufferAddr = rxData;
    gDrvAT25DFObj.memoryAddr = address;

    // gDrvAT25DFObj.state = DRV_AT25DF_STATE_READ_CMD_ADDR; // Remove this line
    gDrvAT25DFObj.state = DRV_AT25DF_STATE_READ_DATA; // Add this line

    if (_DRV_AT25DF_WriteMemoryAddress(DRV_SST26_CMD_HIGH_SPEED_READ, address, 1) == true)
    {
        // ==> This code may be executed after calling _DRV_AT25DF_Handler() <==
        //gDrvAT25DFObj.state = DRV_AT25DF_STATE_READ_DATA; // Remove this line
        isRequestAccepted = true;
    }
    else
    {
        gDrvAT25DFObj.transferStatus = DRV_AT25DF_TRANSFER_STATUS_ERROR;
    }

    return isRequestAccepted;
}`

**Comment by vishalnxt** [comment]
@lucapascarella , Thanks for reporting the issue. It will be fixed in the next release.

**Comment by dsettu** [comment]
@lucapascarella , This issue is fixed now. Please check this out and close. thank you.
